/**
 * Generates the SQL migration for a content wave from chapters.ts —
 * the TS data file is the source of truth; never hand-write the rows.
 *
 * Usage: npx -y tsx scripts/gen-chapter-sql.ts > /tmp/chapter-wave.sql
 */
import { CHAPTER_II, CHAPTER_II_QUEST_SUFFIX } from "../lib/data/chapters";
import { NEIGHBORHOODS } from "../lib/data/neighborhoods";

function dq(text: string): string {
  if (text.includes("$q$")) throw new Error("content contains $q$ delimiter");
  return `$q$${text}$q$`;
}

const lines: string[] = [];

lines.push("-- Generated by scripts/gen-chapter-sql.ts — do not hand-edit rows.");
lines.push("");

for (const n of NEIGHBORHOODS) {
  const chapter = CHAPTER_II[n.id];
  if (!chapter || chapter.length === 0) continue;
  const questId = `${n.id}${CHAPTER_II_QUEST_SUFFIX}`;

  lines.push(
    `insert into public.quests (id, type, name, slug, tagline, description, emoji, color, counts_for_stamp)`,
    `values (${dq(questId)}, 'curated', ${dq(`${n.name} — Chapter II`)}, ${dq(questId)}, ${dq("Five more stops, deeper cuts")}, ${dq(`Second content wave for ${n.name}.`)}, ${dq(n.emoji)}, ${dq(n.color)}, false)`,
    `on conflict (id) do nothing;`,
    "",
  );

  lines.push(
    `insert into public.objectives (id, quest_id, title, description, hint, fun_fact, category, sort_order) values`,
  );
  const rows = chapter.map(
    (o, i) =>
      `(${dq(o.id)}, ${dq(questId)}, ${dq(o.title)}, ${dq(o.description)}, ${dq(o.hint)}, ${o.funFact ? dq(o.funFact) : "null"}, ${dq(o.category)}, ${i + 1})`,
  );
  lines.push(rows.join(",\n") + "\non conflict (id) do nothing;", "");
}

process.stdout.write(lines.join("\n"));
